"ğŸ¯ Feature": ["feature/*", "feat/*"]
"ğŸ›  Refactor": "refactor/*"
"âœ… Test": "test/*"
"ğŸš€ Deploy": "deploy/*"
"ğŸ“ Chore": ["doc/*", "misc/*", "chore/*", "deps/*"]
"ğŸ‘» BugFix": ["fix/*", "fix*"]
"âš™ Setting": ["setting/*", "settings/*"]
"ğŸ‘ğŸ» Review": "*"
